### ISSUE TITLE
Fix document & audio icons alignment

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#174]
SVG styles are a bit off, this is how it is supposed to be: 

![image](https://user-images.githubusercontent.com/9879933/46100861-c5bf4000-c1ca-11e8-90ab-baf4dc6e76db.png)

Correct styles
```css
.anycomment-uploads__item .isvg svg {
    height: 62%;
    margin: 0 auto;
    display: table;
}
```
