### ISSUE TITLE
Bug with dropdown

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#307]
![image](https://user-images.githubusercontent.com/9879933/48424600-43cbac00-e763-11e8-8f9c-fc055aa453a3.png)

Caused by missing position relative on main dropdown element: 

```css
#anycomment-root dropdown--active {
display: relative; 
}
```
