### ISSUE TITLE
Add some like animation

### ISSUE THREAD

**Issue by bologer** [bologer/anycomment.io#316]
To active: 
```css
-webkit-animation: iconToActive 0.4s ease-out;
animation: iconToActive 0.4s ease-out;
```

keyframe: 

```css
@keyframes iconToStatic {
  50% {
    -webkit-transform: scale(0.77);
            transform: scale(0.77);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes iconToActive {
  25% {
    -webkit-transform: scale(0.77);
            transform: scale(0.77);
  }
  75% {
    -webkit-transform: scale(1.55);
            transform: scale(1.55);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
```
